version: "3.9"

services:
  web:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn dev -o"
    ports:
      - "3000:3000"
    env_file:
      #  .env.development in dev
      - ${ENV_FILE}
